export const orderStateDataExample = [
    {
        id: 0,
        pk: ['ob2htHLoCu2P6tX7RrNVtiG1mYTas8NGJEVLaFEUngk', 'uja3w9XG1g6DQSVT6YASK99FVmdVwXoHVoQEgtEJdLv', '4C3Fcao9TNaXqQvDSpV17xpeYKf4mMsM9K1fdbnMowos', '9McMPfjkLQFtuqV8unL824L4bp2JmogUtyXw6VcXaRGD', '6rT4QuXgdgFVSWNkj6VHjthRXSfFyPy1XQqHTtf1QLjE', '496JNc5TbqruWApDoq6cy5DzDrzJSTZiCuVv4Py136Yi', '2yoNTWPTMLW7hyA94156VBUtpiRNbDm9C7WXe2s2P14z', 'emhWqBszq4NzVY2E52rcB9zG3GvdNNDefqcXM2zoQjg', 'DCAKxn5PFNN1mBREPWGdk1RXg5aVH9rPErLfBFEi2Emb', 'E7iPLWfFKKtSNqLnGji92cHtYESBNfZzXLdDPhJjcGmK']
    }
]

export const orderDataExample = [
    {
        id: 0,
        placed: 1715911593,
        owner: '4C3Fcao9TNaXqQvDSpV17xpeYKf4mMsM9K1fdbnMowos',
        tokenAddress: 'AzNUW1A2sMXhQeW1xgo9nwLLcE2fqYmP7tqdyMCSs2ib',
        tokenName: 'Alien Shiba',
        tokenTicker: 'ALIEN',
        tokenImage: 'https://cf-ipfs.com/ipfs/QmbuqiuKeNBhBhswTfAoPY2LUZqmhEtRmBrjTJkSGD3A2B',
        bumpPackage: 1,
        botNbr: 3,
        frequency: 60,
        duration: 24,
        funding: 10,
        status: 'pending',
        fee: 2,
    },
    {
        id: 1,
        placed: 1715911593,
        owner: '9McMPfjkLQFtuqV8unL824L4bp2JmogUtyXw6VcXaRGD',
        tokenAddress: 'CtjTFRa63j4TQZ5LPzHLUAFXfYt7p5ib31YrMvjEbTab',
        tokenName: 'BumPill',
        tokenTicker: 'BP',
        tokenImage: 'https://cf-ipfs.com/ipfs/QmR6Kdjz7nU3Xw9ea77kYX5wwJDaeSHMFvsSfMJ3QJcPp3',
        bumpPackage: 2,
        botNbr: 10,
        frequency: 30,
        duration: 24,
        funding: 10,
        status: 'live',
        fee: 2,
    },
    {
        id: 2,
        placed: 1715911593,
        owner: '6rT4QuXgdgFVSWNkj6VHjthRXSfFyPy1XQqHTtf1QLjE',
        tokenAddress: 'GxPKti4oZ688Br8v5vGvp5fVNSVFCr5vmga25ZXQ3D81',
        tokenName: 'RELONIO',
        tokenTicker: 'RELONIO',
        tokenImage: 'https://cf-ipfs.com/ipfs/QmQpzXYY8kCSvLgbBiiiprWDCWrHFaWHcvHJ9FXzjrQrJp',
        bumpPackage: 3,
        botNbr: 25,
        frequency: 5,
        duration: 24,
        funding: 10,
        status: 'canceled',
        fee: 2,
    },
    {
        id: 3,
        placed: 1715911593,
        owner: '496JNc5TbqruWApDoq6cy5DzDrzJSTZiCuVv4Py136Yi',
        tokenAddress: 'Frq2p2JRFwi9Khyrm4f2Qt7a1RTEqpus5yZc4xcYuCZt',
        tokenName: 'Evil Cat',
        tokenTicker: 'ECAT',
        tokenImage: 'https://cf-ipfs.com/ipfs/QmVz51DLXdyRvo62bBJ2NBUcoSAckBwBbrkEdX6hwhH8RR',
        bumpPackage: 1,
        botNbr: 3,
        frequency: 30,
        duration: 24,
        funding: 10,
        status: 'finished',
        fee: 2,
    },
]